#!/bin/bash

source /global/homes/m/mperego/cori_modules.sh
module unload craype-hugepages2M 

# note this version has no netcdf support 
PIO=/global/homes/m/mperego/piscees/mpas/TPL/pio/pio-build/install

source /global/homes/m/mperego/albany/albany-build/install-mali-sfad8/export_albany.in
#source /global/homes/t/tongz/apps/MPAS-Model-Opt/export_albany.in.new

MPAS_EXTERNAL_LIBS="$ALBANY_LINK_LIBS -lstdc++"

CORE=landice

make clean gnu-nersc ALBANY=true USE_PIO2=true CORE=$CORE PIO=$PIO MPAS_EXTERNAL_LIBS="$MPAS_EXTERNAL_LIBS" DEBUG=true 
#make clean gnu-nersc ALBANY=false USE_PIO2=true CORE=$CORE PIO=$PIO DEBUG=true 


